name: Robot de Instagram Santas

on:
  schedule:
    # Hora UTC. Colombia es UTC-5.
    # Miércoles a las 2:00 PM COT = 19:00 UTC (Corremos a la 1:55 PM / 18:55 UTC)
    - cron: '55 18 * * 3'
    # Viernes a las 7:00 PM COT = 00:00 UTC del Sábado (Corremos a las 6:55 PM / 23:55 UTC)
    - cron: '55 23 * * 5'
  workflow_dispatch: # Permite correrlo manualmente con un botón para probar

jobs:
  escanear-historias:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install playwright supabase
          playwright install chromium

      - name: Ejecutar Robot Verificador
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          IG_USER: ${{ secrets.IG_USER }}
          IG_PASS: ${{ secrets.IG_PASS }}
        run: python robot.py
