name: Robot de Instagram Santas

on:
  schedule:
    - cron: '55 18 * * 3'
    - cron: '55 23 * * 5'
  workflow_dispatch: 

jobs:
  escanear-historias:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Bajamos a 3.10 para mayor estabilidad

      - name: Instalar dependencias
        run: |
          pip install supabase==2.0.3 playwright
          playwright install chromium

      - name: Ejecutar Robot Verificador
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          IG_USER: ${{ secrets.IG_USER }}
          IG_PASS: ${{ secrets.IG_PASS }}
        run: python robot.py
